T = {
    "English": {
        "title": "Ad Budget Planner",
        "subtitle": "See whether your current ad spend is healthy, too high, or safe to scale.",

        "biz_stage": "Choose your situation",
        "новый_бизнес": "New business",
        "existing_business": "Existing business",

        "mode": "Choose input mode",
        "m_manual": "Enter business numbers manually",
        "m_csv": "Upload ad report (CSV / XLSX)",
        "m_funnel": "Enter ad funnel manually",

        "rev": "Total revenue",
        "cogs": "Total product cost",
        "spend": "Current ad spend",
        "orders": "Orders",
        "refund": "Return rate (%)",

        "upload_meta": "Upload ad report",
        "upload_csv": "Upload CSV / XLSX",
        "upload_hint": "Upload an ad report to auto-fill spend and conversations. Then enter average order value, product cost, and conversion rate.",
        "preview": "Preview",

        "camp_col": "Campaign name column",
        "spend_col": "Ad spend column",
        "results_col": "Results column",
        "indicator_col": "Result type column",
        "select_campaigns": "Select campaigns to include",

        "derived": "### Detected from file",
        "bridge": "Connect ad report to business numbers",

        "close_rate": "Conversation-to-order rate",
        "aov": "Average order value",
        "cogs_po": "Product cost per order",

        "manual_funnel_header": "Enter ad funnel data manually",
        "spend_f": "Ad spend",
        "convos": "Conversations",
        "clicks": "Clicks (optional)",
        "impr": "Impressions (optional)",

        "scale_header": "Scenario settings",
        "preset_label": "How does ad efficiency usually change when you scale?",
        "preset_opt": "Optimistic",
        "preset_real": "Realistic",
        "preset_bad": "Pessimistic",
        "scale_inc": "Planned budget change (%)",
        "scale_decay": "If you double spend, how much can customer acquisition cost rise (%)?",
        "note": "Example: if acquiring a customer currently costs 20 and this is set to 25%, the model assumes that cost may rise to around 25 when you double your budget.",

        "analyze": "Calculate",

        "no_msg_rows": "No messaging rows found in the selected result type column.",
        "msg_fallback_all": "No messaging rows found. Using all selected rows instead.",
        "indicator_values": "Unique values in the selected result type column:",
        "conv_zero": "Conversations total is 0. Cannot continue.",
        "warn_orders": "Estimated orders are below 1. Using 1 order to avoid division by zero.",
        "warn_convos": "Conversations must be greater than 0 for this mode.",

        "status_hold": "🔴 STOP — Economics are weak or scaling leads to a loss.",
        "status_fragile": "🟠 CAUTION — A small drop in efficiency can break profitability.",
        "status_safe": "🟢 OK — Economics can handle some growth.",

        "bottleneck_neg": "Economics are negative even before ad spend.",
        "bottleneck_cac": "Main risk: customer acquisition cost is too high.",
        "bottleneck_ref": "Returns are eating into profit.",
        "bottleneck_margin": "Low margin limits safe growth.",
        "bottleneck_ok": "No major structural problem detected.",

        "risk_hdr": "Risk level",
        "baseline_hdr": "Current situation",
        "unit_hdr": "Order economics",
        "safe_cac_hdr": "Safe customer acquisition cost",
        "max_budget_hdr": "Maximum safe ad budget",
        "real_analysis_hdr": "Current numbers breakdown",
        "ads_effect_hdr": "Are ads helping or hurting right now?",
        "next_move_hdr": "What to do next",
        "main_constraint": "Main problem",
        "rec_hdr": "Recommendation",
        "main_insight_hdr": "Main takeaway",
        "sim_hdr": "Selected scenario result",
        "safe_hdr": "Safe budget increase limit",
        "safe_line": "How much you can increase budget before profit turns negative",
        "low_ceiling": "Small buffer: aggressive budget increases may quickly push you into a loss.",
        "table_hdr": "Scenario table",

        "chart_hdr": "How profit changes with budget",
        "chart_note": "Shows where changing the budget helps profit and where it starts to hurt.",
        "current_point": "Current point",
        "peak_point": "Best profit point",
        "breakeven_point": "Loss point",
        "peak_profit": "Best profit",
        "peak_spend": "Best ad budget",
        "profit_cliff": "Beyond a certain point, further budget increases reduce total profit.",

        "safe_cac": "Safe acquisition cost",
        "current_cac": "Current acquisition cost",
        "margin_buffer": "Profit buffer per order",

        "current_ad_spend": "Current ad budget",
        "max_safe_spend": "Maximum safe budget",
        "loss_point_spend": "Budget where profit turns negative",
        "profit_before_ads": "Profit before ads",
        "profit_after_ads": "Profit after ads",
        "ad_impact": "Ad impact on profit",

        "forecast_spend": "Projected spend",
        "forecast_cac": "Projected acquisition cost",
        "forecast_orders": "Projected orders",
        "forecast_revenue": "Projected revenue",
        "forecast_profit": "Projected profit",

        "spend_increase_col": "Budget change %",
        "status_col": "Status",

        "newbiz_header": "New business plan",
        "planned_budget": "Planned ad budget",
        "expected_cac": "Expected cost to acquire one customer",
        "target_profit": "Target profit (optional)",
        "expected_orders": "Expected customers",
        "expected_revenue": "Expected revenue",
        "expected_profit": "Expected profit",
        "rec_budget": "Suggested test budget",
        "newbiz_result": "Preliminary estimate for new business",
        "newbiz_note": "Use this mode if you are planning your first ad campaign and have no real data yet.",

        "example_btn": "Load example data",

        "reco_neg": "Economics are negative before ads. Fix pricing, product cost, or return rate first.",
        "reco_refund": "Return rate is too high. Scaling ads now will amplify losses. Fix product quality or customer expectations first.",
        "reco_margin": "Profit per order is too thin. Raise average order value or reduce product cost before increasing budget.",
        "reco_cac_close": "Acquisition cost is already too close to the break-even limit. Grow carefully or improve conversion first.",
        "reco_good": "Good profit buffer. You still have room before hitting the acquisition cost limit.",
        "reco_mid": "Numbers look workable, but watch whether acquisition cost rises as you scale.",

        "insight_drop_pct": "If budget changes by {pct}%, profit may fall by {value}.",
        "insight_grow_pct": "If budget changes by {pct}%, profit may improve by {value}.",
        "insight_safe_limit": "You can safely increase budget by up to {pct}% before profit turns negative.",
        "insight_cac_ratio": "Current acquisition cost is already {pct}% of the safe level.",

        "meta_diag": "Additional ad metrics (optional)",
        "cost_per_convo": "Cost per conversation",
        "conv_to_order": "Conversation-to-order rate",
        "estimated_cac": "Estimated acquisition cost",
        "ctr": "Click-through rate",
        "cpc": "Cost per click",
        "click_to_convo": "Click-to-conversation rate",

        "ads_destroying": "Ads are currently pushing the business into a loss.",
        "ads_ok": "Ads are still profitable at the current budget level.",
        "ads_weak": "Ads are still profitable, but efficiency is weakening.",
        "ads_not_problem": "The main problem is the core business economics, not the ad budget.",
        "reduce_spend": "Reduce ad budget",
        "hold_spend": "Keep current budget",
        "scale_gradually": "Increase budget gradually",
        "fix_conversion": "Improve conversion first",
        "fix_refunds": "Fix returns problem first",
        "fix_margin": "Improve profit per order first",
        "overspending_now": "Current budget appears to be above the peak profit point.",
        "reducing_can_help": "Reducing budget may improve profit.",
        "current_close_to_peak": "Current budget is already close to the most profitable zone.",
        "still_room_to_scale": "There is still room to grow before reaching peak profit.",
    },
    "Русский": {
        "title": "Планировщик рекламного бюджета",
        "subtitle": "Помогает понять, не слишком ли много вы тратите на рекламу и можно ли безопасно увеличить бюджет.",

        "biz_stage": "Выберите вашу ситуацию",
        "новый_бизнес": "Новый бизнес",
        "existing_business": "Есть действующий бизнес",

        "mode": "Выберите способ ввода",
        "m_manual": "Ввести цифры бизнеса вручную",
        "m_csv": "Загрузить рекламный отчёт",
        "m_funnel": "Ввести рекламную воронку вручную",

        "rev": "Общая выручка",
        "cogs": "Общая себестоимость",
        "spend": "Текущий расход на рекламу",
        "orders": "Заказы",
        "refund": "Процент возвратов (%)",

        "upload_meta": "Загрузить рекламный отчёт",
        "upload_csv": "Загрузить файл отчёта",
        "upload_hint": "Загрузите рекламный отчёт, чтобы автоматически подтянуть расходы и количество обращений. Затем введите средний чек, себестоимость и конверсию в покупку.",
        "preview": "Предпросмотр",

        "camp_col": "Колонка с названием кампании",
        "spend_col": "Колонка с расходом на рекламу",
        "results_col": "Колонка с результатами",
        "indicator_col": "Колонка с типом результата",
        "select_campaigns": "Выберите рекламные кампании",

        "derived": "### Получено из файла",
        "bridge": "Свяжите рекламный отчёт с бизнес-цифрами",

        "close_rate": "Конверсия в покупку",
        "aov": "Средний чек",
        "cogs_po": "Себестоимость одного заказа",

        "manual_funnel_header": "Ручной ввод данных по рекламе",
        "spend_f": "Расход на рекламу",
        "convos": "Обращения",
        "clicks": "Клики (необязательно)",
        "impr": "Показы (необязательно)",

        "scale_header": "Настройки расчёта",
        "preset_label": "Как обычно ведёт себя реклама, когда вы увеличиваете бюджет?",
        "preset_opt": "Лучший вариант",
        "preset_real": "Средний вариант",
        "preset_bad": "Худший вариант",
        "scale_inc": "На сколько хотите изменить рекламный бюджет (%)",
        "scale_decay": "Если увеличить бюджет в 2 раза, на сколько может вырасти стоимость привлечения клиента (%)?",
        "note": "Пример: если сейчас привлечение одного клиента стоит 20, а здесь стоит 25%, то при удвоении бюджета модель предполагает рост этой стоимости примерно до 25.",

        "analyze": "Рассчитать",

        "no_msg_rows": "В выбранной колонке не найдено строк, связанных с сообщениями.",
        "msg_fallback_all": "Строки с сообщениями не найдены. Используются все выбранные строки.",
        "indicator_values": "Уникальные значения в выбранной колонке:",
        "conv_zero": "Количество обращений = 0. Невозможно продолжить расчёт.",
        "warn_orders": "Расчётные заказы меньше 1. Используется 1 заказ, чтобы избежать деления на ноль.",
        "warn_convos": "Количество обращений должно быть больше 0 для этого режима.",

        "status_hold": "🔴 СТОП — Сейчас экономика слабая или рост бюджета ведёт к убытку.",
        "status_fragile": "🟠 ОСТОРОЖНО — Даже небольшое ухудшение может сильно снизить прибыль.",
        "status_safe": "🟢 НОРМАЛЬНО — Экономика выдерживает некоторый рост.",

        "bottleneck_neg": "Экономика отрицательная ещё до рекламы.",
        "bottleneck_cac": "Главный риск сейчас — слишком дорогой клиент.",
        "bottleneck_ref": "Возвраты съедают прибыль.",
        "bottleneck_margin": "Низкая маржа ограничивает безопасный рост.",
        "bottleneck_ok": "Серьёзных проблем не видно.",

        "risk_hdr": "Уровень риска",
        "baseline_hdr": "Текущая ситуация",
        "unit_hdr": "Экономика заказа",
        "safe_cac_hdr": "Безопасная стоимость клиента",
        "max_budget_hdr": "Максимально безопасный бюджет на рекламу",
        "real_analysis_hdr": "Разбор текущих цифр",
        "ads_effect_hdr": "Реклама сейчас помогает или мешает?",
        "next_move_hdr": "Что делать дальше",
        "main_constraint": "Главная проблема",
        "rec_hdr": "Рекомендация",
        "main_insight_hdr": "Главный итог",
        "sim_hdr": "Результат выбранного прогноза",
        "safe_hdr": "Предел безопасного увеличения бюджета",
        "safe_line": "Насколько можно увеличить бюджет, прежде чем прибыль уйдёт в минус",
        "low_ceiling": "Запас небольшой: если резко увеличивать бюджет, можно быстро уйти в минус.",
        "table_hdr": "Таблица сценариев",

        "chart_hdr": "Как меняется прибыль при изменении бюджета",
        "chart_note": "Показывает, где изменение бюджета помогает прибыли, а где уже начинает вредить.",
        "current_point": "Текущая точка",
        "peak_point": "Лучшая точка по прибыли",
        "breakeven_point": "Точка ухода в убыток",
        "peak_profit": "Лучшая прибыль",
        "peak_spend": "Лучший бюджет на рекламу",
        "profit_cliff": "После определённой точки дальнейший рост бюджета снижает общую прибыль.",

        "safe_cac": "Безопасная стоимость клиента",
        "current_cac": "Текущая стоимость клиента",
        "margin_buffer": "Запас прибыли с заказа",

        "current_ad_spend": "Текущий бюджет на рекламу",
        "max_safe_spend": "Максимально безопасный бюджет",
        "loss_point_spend": "Бюджет, при котором прибыль уходит в минус",
        "profit_before_ads": "Прибыль до рекламы",
        "profit_after_ads": "Прибыль после рекламы",
        "ad_impact": "Влияние рекламы на прибыль",

        "forecast_spend": "Расходы в расчёте",
        "forecast_cac": "Стоимость клиента в расчёте",
        "forecast_orders": "Заказы в расчёте",
        "forecast_revenue": "Выручка в расчёте",
        "forecast_profit": "Прибыль в расчёте",

        "spend_increase_col": "Изменение бюджета, %",
        "status_col": "Статус",

        "newbiz_header": "План для нового бизнеса",
        "planned_budget": "Планируемый бюджет на рекламу",
        "expected_cac": "Ожидаемая стоимость одного клиента",
        "target_profit": "Желаемая прибыль (необязательно)",
        "expected_orders": "Ожидаемое число клиентов",
        "expected_revenue": "Ожидаемая выручка",
        "expected_profit": "Ожидаемая прибыль",
        "rec_budget": "Рекомендуемый бюджет на проверку",
        "newbiz_result": "Предварительный расчёт для нового бизнеса",
        "newbiz_note": "Используйте этот режим, если вы только планируете первый запуск рекламы и у вас ещё нет реальных цифр.",

        "example_btn": "Подставить пример",

        "reco_neg": "Экономика отрицательная ещё до рекламы. Сначала пересмотрите цену, себестоимость или уровень возвратов.",
        "reco_refund": "Процент возвратов слишком высокий. Рост рекламы усилит убытки. Сначала исправьте качество продукта или ожидания клиентов.",
        "reco_margin": "Прибыль с заказа слишком маленькая. Лучше повысить средний чек или снизить себестоимость перед ростом бюджета.",
        "reco_cac_close": "Стоимость клиента уже слишком близка к опасной границе. Лучше расти осторожно или сначала улучшить продажи.",
        "reco_good": "Хороший запас прибыли. У вас ещё есть пространство до точки безубыточности.",
        "reco_mid": "Цифры пока выглядят рабочими, но при росте бюджета следите, не дорожает ли клиент.",

        "insight_drop_pct": "Если изменить рекламный бюджет на {pct}%, прибыль может снизиться на {value}.",
        "insight_grow_pct": "Если изменить рекламный бюджет на {pct}%, прибыль может вырасти на {value}.",
        "insight_safe_limit": "Бюджет можно безопасно увеличить максимум на {pct}%, прежде чем прибыль уйдёт в минус.",
        "insight_cac_ratio": "Текущая стоимость клиента уже составляет {pct}% от безопасного уровня.",

        "meta_diag": "Дополнительные показатели рекламы (необязательно)",
        "cost_per_convo": "Стоимость обращения",
        "conv_to_order": "Конверсия в покупку",
        "estimated_cac": "Расчётная стоимость клиента",
        "ctr": "Доля кликов",
        "cpc": "Стоимость клика",
        "click_to_convo": "Конверсия из клика в обращение",

        "ads_destroying": "Сейчас реклама уводит бизнес в минус.",
        "ads_ok": "Сейчас реклама ещё приносит прибыль.",
        "ads_weak": "Реклама пока приносит прибыль, но уже слабеет.",
        "ads_not_problem": "Главная проблема сейчас не в рекламе, а в самой экономике бизнеса.",
        "reduce_spend": "Снизить бюджет на рекламу",
        "hold_spend": "Оставить текущий бюджет",
        "scale_gradually": "Увеличивать бюджет постепенно",
        "fix_conversion": "Сначала улучшить продажи",
        "fix_refunds": "Сначала решить проблему возвратов",
        "fix_margin": "Сначала увеличить прибыль с заказа",
        "overspending_now": "Текущий бюджет на рекламу, похоже, выше точки максимальной прибыли.",
        "reducing_can_help": "Снижение бюджета может увеличить прибыль.",
        "current_close_to_peak": "Текущий бюджет уже близок к лучшей зоне по прибыли.",
        "still_room_to_scale": "До лучшей точки по прибыли у вас ещё есть запас для роста.",
    },
}
